import type { Metadata } from "next";
import '@/styles/globals.css';


export const metadata: Metadata = {
  title: "Remote Kitchen",
  description: "Generated by Khairul Islam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        </body>
    </html>
  );
}
